<?php
	$projects = array('Solomon Islands',
		'New Zealand',
		'Papua New Guinea',
		'Indonesia');
?>
<div id="projects">
	<?php 

		$headings = '<div class="headings">';
		$content = '<div class="project-container">';
		$select = '<div class="select-project"><p>Select a Country to View Projects</p>';
		$images = '<div class="images">';	
	
		foreach($projects as $project){

			$id = str_replace(' ', '', strtolower($project));
			$headings .= '<h2 data-target="'.$id.'"><a>'.$project.'</a></h2>';
			$image = '<img data-target = "'.$id.'" src="images/countries/'.$id.'.jpg?3" alt="'.$project.'">';

			$description = $this->render('projects/partials/'.$id.'/data.phtml');
		
			$content .= '<div id="'.$id.'-content" class="project-content">'.$image;
			$content .= '<div class="description">'.$description.'</div></div>';
			$images .= $image;
		}

		$headings .= '</div>';
		$images .= '</div>';
		$content .= '</div>';		
		$select .= $images.'</div>';

		echo($headings.$select.$content);
	?>
</div>

<script type="text/javascript">

	$(document).ready(function(){
		$('.headings h2').hover(function(){
			var target = $(this).attr('data-target');
			$(this).find('a').addClass('hover', 1000);
			$('.images img[data-target="'+target+'"]').css('opacity',1).css('filter', ':alpha(opacity=100)');
		}, function()
		{
			var target = $(this).attr('data-target');
			$('.images img[data-target="'+target+'"]').css('opacity',0.4).css('filter', ':alpha(opacity=40)');
			$(this).find('a').removeClass('hover', 1000);
		});

		$('.images img').hover(function(){
			var target = $(this).attr('data-target');
			$(this).css('opacity',1).css('filter', ':alpha(opacity=100)');			
			$('.headings h2[data-target="'+target+'"] a').addClass('hover');
		}, function()
		{
			var target = $(this).attr('data-target');
			$(this).css('opacity',0.4).css('filter', ':alpha(opacity=40)');			
			$('.headings h2[data-target="'+target+'"] a').removeClass('hover');
		});

		$('.headings h2').click(function(){

			var target = $(this).attr('data-target');		
			openContent(target);
		});

		$('.images img').click(function(){

			var target = $(this).attr('data-target');		
			openContent(target);
		});

		function openContent(target)
		{
			headingId = target  + '-content';

			$('.select-project').remove();

			$('.headings h2').removeClass('selected');

			$('.project-content').hide();
			$('#' + headingId).show();

			$('.headings h2[data-target="'+target+'"]').addClass('selected');
		}
	});	
</script>