<h2>Senior Advisor – Newmont Asia Pacific</h2>

<p>Newmont Asia Pacific is a major mining company and the second largest producer of the world’s gold.</p>

<p>Newmont Ventures Ltd – Papua New Guinea – Bulolo Project</p>

<ul>
<li>To act as an In-Country Advisor on Community Relations, Stakeholder Engagement and Conflict Resolution strategies.</li>
<li>To improve and enhance internal cross functional relationships.</li>
<li>The redesign, development and implementation of policies, processes, systems and standard operating procedures to enhance the efficiencies of the Social Responsibility systems.</li>
<li>Train and build the capacity and capability of national Papua New Guinea Community Relations staff.</li>
</ul>
