<h1>Testimonials</h1>
<p>
“John’s key strengths are: he is a team player, staff selection, training and mentoring, the ability to quickly develop and continually improve a CR management operating system, a strong work ethic and high productivity, a natural understanding and affinity with customary management and negotiation skills are also invaluable”  </p><p><i>Craig Miller- Exploration Business Development Manager Newmont Asia Pacific</i></p>

<p>“John is especially skilled in working with stakeholders from diverse ethnic backgrounds; he can be relied upon to work independently with them to achieve win/win results”</p>

<p>“John is not interested in popularity; he is driven to do what is right” </p><p><i>Kay Read- General Manager, Tenancy Services Housing New Zealand Corporation</i></p>

<p>“John was often used as the "go to person" within Housing New Zealand Corporation and Pacific Porphyry SI Ltd to resolve long-standing and highly complex problems”</p>

<p>“John is the man you want in your organization who will break down silos, create empowered and productive teams and deliver on the most difficult assignments.” </p><p><i>Jaime Reibel- International Development Project Manager</i></p>

<p>“Today was farewell for JK. It was truly emotional and yes your experiences shared in your path of life amazes me further to appreciate life and ones value in life...
You are rare and we all are special to have come across you in our lives. Memories linger as you are one of those people we love working with above all with fun.</p>

<p>Go well with all our blessings from PNG..."</p><p><i>Cheryl Kisaku – Project Accountant – Newmont Ventures Ltd – Bulolo – Papua New Guinea</i></p>

<p>“John is ready to take on very senior roles. He is a keen learner, great at listening to people’s views and also works very well under pressure. I have no hesitation in recommending John to a senior role in any organization.” </p><p><i>Baoro Laxton Koraua- General Manager Pacific Porphyry SI Ltd.</i></p>

<p>“I work with John Kaimarama while he’s the Manager for Community and Government Relations. He has done a good job with Pacific Porphyry SI Ltd. He can work with any ethnic group in the Solomon Islands"</p>

<p><i>May 5, 2013, Ivan Leanamae; Superintendent Community & Government Relations at Pacific Porphyry SI Ltd. Solomon Islands. <br/>Ivan worked directly with John at Pacific Porphyry SI Ltd, Solomon Islands</i></p>