<h3>Director Pacifika Consultants Ltd</h3>

<p>Negotiated a 12 month contract on retainer with Newmont Asia Pacific, a major Gold Mining Company widely regarded as the world’s second largest gold producer.</p>

<p>Project 1:	To project manage the reconfiguration of an Environmental project at the Newmont Tanami Operations, the most remote mine site in Australia which involved:</p>

<ul>
	<li>The audit and rehabilitation of 13500 drill holes at the Newmont Tanami Operations, the most remote mine site in Australia</li>
	<li>Source and appoint a rehabilitation contractor</li>
	<li>To project manage the development and implementation a new system drill hole register system to be implemented regionally by the Exploration division of Newmont Asia Pacific.</li>
	<li>To enhance the employment opportunities of local Traditional Owners.</li>
</ul>

<p>Project 2: To project manage the stakeholder engagement project involving 7 tribal authorities in the Hauraki District for the Newmont Waihi Gold Mine based in New Zealand. The project is to involve:</p> 

<p>Strategy development:</p>
<ul>
<li>Key players</li> 
<li>Inter and intra Iwi relationships </li>
<li>Community/tribal view of mining: from the Collective and individual Iwi</li>
Other influential factors</li>
<li>Recommendation of an engagement strategy to the company</li>

</ul>

<h3>Housing New Zealand Corporation</h3>

<p>Manager, Special Projects</p>
<ul>
	<li>formulated and delivered advice to National and Delivery Managers, and staff  on Housing Partnership products</li>
	<li>planned and managed delivery of a review of the Rural Housing Programme, including engaging, motivating and empowering up to 55 multi-disciplinary team</li>
	<li>Co-facilitate the project management of the Māori Partnership project across the HNZC, including negotiating with Māori tribes and Iwi organisations</li>
	<li>fostering internal staff and stakeholder relationships and providing operational policy advice on housing with a focus on Māori</li>
	<li>developing a Staff Satisfaction Plan for the Housing Partnership to enhance morale</li>
</ul>

<p>Delivery Manager Northern Region</p>
<ul>
<li>trained and managed performance of fifteen staff</li>
<li>formulated and implemented strategies to resolve sub-standard housing within rural Māori communities</li>
<li>managed operational activities to coordinate construction of new community housing and maintenance and repair of existing properties</li>
<li>undertook a review of systems and procedures to identify business weaknesses, develop and propose change methods</li>
<li>brokered strategic alliances with commercial building and tribal service providers to improve procurement of materials for construction of rural housing</li>
<li>devised an innovative methodology based on shared services between Housing Innovations and Housing Services to enhance working environment for regional staff</li>
<li>led construction projects, including 20 cooperative community builds and 200 essential repairs</li>
</ul>

