<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="description=" content="<?php echo($this->metaDescription);?>">
  <?php echo($this->headTitle());?>
  <?php echo $this->headLink()->appendStylesheet('/css/screen.css') ?>
  <?php echo $this->headScript()->appendFile('/node_modules/jquery/lib/node-jquery.js')?>
</head>
<body>
  <?php echo $this->layout()->content ?> 
</body>
</html>