<!DOCTYPE html>
	<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
	<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
	<head>
	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	  <meta name="description=" content="<?php echo($this->metaDescription);?>">
	  <?php echo($this->headTitle());?>
	  <?php echo $this->headLink()->appendStylesheet('/css/screen.css') ?>
	  <?php echo $this->headLink()->appendStylesheet('/css/foundation/normalize.css') ?>
	  <?php echo $this->headLink()->appendStylesheet('/css/foundation/foundation.min.css') ?>
	  <?php echo $this->headScript()->appendFile('/node_modules/jquery/lib/node-jquery.js')?>
	  <link rel="icon" 
	      type="image/png" 
	      href="/images/structure/icon.png">
	</head>
	<body>
		<div class="row">
			<div class="columns">
			  	<?php echo $this->render('nav.phtml');?>
			 	<?php echo $this->layout()->content ?> 
			</div>
		</div>
		<script src="js/foundation.min.js"></script>
		<script src="js/foundation/foundation.topbar.js"></script>
		<script>
			$(document).foundation();
		</script>
	</body> 
</html>