<?php 
	$sections = array('Home' => '/',
		'About' => '/about',	
		'Projects' => '/projects',	
		'Testimonials' => '/testimonials',		
		'Contact'=> '/contact'	
		);
?>
<!-- Large Nav -->
<div class="fixed">
	<nav class="top-bar">
		<ul class="title-area">
			<li class="name"></li>			
			<li class="toggle-topbar menu-icon">
				<a href><span>Menu</span></a>
			</li>			
		</ul>
		<section class="top-bar-section">			
			<ul class="left">
				<?foreach ($sections as $section => $url)
				{
					$active = $this->request->getRequestUri() == $url ? 'active' : '';
					echo('<li class="'.$active.'"><a href="'.$url.'">'.$section.'</a></li>');
				}
				?>			
			</ul>
		</section> 
	</nav>
</div>
