<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Pacifika Consultants');?>

        <?php echo $this->headMeta()->appendName('description', 'Pacifika Consultants') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/small-logo.ico'))
                        ->prependStylesheet($this->basePath() . '/css/foundation.min.css')
                        ->prependStylesheet($this->basePath() . '/css/normalize.css')
                        ->prependStylesheet($this->basePath() . '/css/screen.css')?>
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/jquery-1.10.1.min.js')
                                      ->prependFile($this->basePath() . '/js/vendor/custom.modernizr.js')?>
        <script type="text/javascript" src="/js/flip/jquery.flippy.js"></script>
        <script type="text/javascript" src="/js/jquery-ui/jquery-ui.min.js"></script>
    </head>
    <body>
        <div class="row">
            <div class="large-12 columns">
                <?php echo $this->content; ?>
            </div>
        </div>
        <script>
            document.write('<script src=/js/vendor/'
                + ('__proto__' in {} ? 'zepto' : 'jquery')
                + '.js><\/script>');
        </script>
        <script src="/js/foundation.min.js"></script>
        <script>
            $(document).foundation();
        </script>
    </body>
</html>
