<h2>Director Pacifika Consultants Ltd</h2>

<p>Negotiated a 12 month contract on retainer with Newmont Asia Pacific, a major Gold Mining Company widely regarded as the world’s second largest gold producer.</p>

<p>Project 1:	To project manage the reconfiguration of an Environmental project at the Newmont Tanami Operations, the most remote mine site in Australia which involved:</p>

<ul>
	<li>The audit and rehabilitation of 13500 drill holes at the Newmont Tanami Operations, the most remote mine site in Australia</li>
	<li>Source and appoint a rehabilitation contractor</li>
	<li>To project manage the development and implementation a new system drill hole register system to be implemented regionally by the Exploration division of Newmont Asia Pacific.</li>
	<li>To enhance the employment opportunities of local Traditional Owners.</li>
</ul>

<p>Project 2: To project manage the stakeholder engagement project involving 7 tribal authorities in the Hauraki District for the Newmont Waihi Gold Mine based in New Zealand. The project is to involve:</p> 

<p>Strategy development:</p>
<ul>
<li>Key players</li> 
<li>Inter and intra Iwi relationships </li>
<li>Community/tribal view of mining: from the Collective and individual Iwi</li>
Other influential factors</li>
<li>Recommendation of an engagement strategy to the company</li>
