<h2>Housing New Zealand Corporation</h2>

<p>Manager, Special Projects</p>
<ul>
	<li>formulated and delivered advice to National and Delivery Managers, and staff  on Housing Partnership products</li>
	<li>planned and managed delivery of a review of the Rural Housing Programme, including engaging, motivating and empowering up to 55 multi-disciplinary team</li>
	<li>Co-facilitate the project management of the Māori Partnership project across the HNZC, including negotiating with Māori tribes and Iwi organisations</li>
	<li>fostering internal staff and stakeholder relationships and providing operational policy advice on housing with a focus on Māori</li>
	<li>developing a Staff Satisfaction Plan for the Housing Partnership to enhance morale</li>
</ul>

<p>Delivery Manager Northern Region</p>
<ul>
<li>trained and managed performance of fifteen staff</li>
<li>formulated and implemented strategies to resolve sub-standard housing within rural Māori communities</li>
<li>managed operational activities to coordinate construction of new community housing and maintenance and repair of existing properties</li>
<li>undertook a review of systems and procedures to identify business weaknesses, develop and propose change methods</li>
<li>brokered strategic alliances with commercial building and tribal service providers to improve procurement of materials for construction of rural housing</li>
<li>devised an innovative methodology based on shared services between Housing Innovations and Housing Services to enhance working environment for regional staff</li>
<li>led construction projects, including 20 cooperative community builds and 200 essential repairs</li>
</ul>
