<h3>Newmont Asia Pacific</h3>

<p>Newmont Asia Pacific is a major mining company and is considered the second largest producer of the world’s gold.</p>

<p>Batu Hijau Mine – Sumbawa Island, Indonesia</p>

<ul><li>
<p>Project:	 Implementation of a new systems and procedures process for the Community Relations section of the Generative Exploration division for the mine site. To perform an environmental scan of the Community Relations functions of the mine, report back and make recommendations for efficiency improvements.</li></p></ul>
