<h2>Solomon Islands – Pacific Porphyry SI Ltd. subsidiary of XDM Resources</h2>

<p>Mineral Extractive Industry - Generative Exploration – Gold & Copper</p>

<p>Project was based in the Solomon Islands and predominantly in the Western Province (Morovo Lagoon, New Georgia Island, Vela Lavela Island). Three projects were completed over a 2 year period being:</p>

<ul>
<li>Project 1: 	A business improvement process for 4 tenement camps which involved an environmental scan of all logistical systems, recommendation and redesign of systems, implementation process. The outcome was operational efficiencies resulting in a reduction of operational costs.</li>

<li>Project 2:	As Manager of Community Development & Government Relations I led a team that achieved and negotiated the renewal of four Prospecting Licenses, six Surface Access Agreements, and one new Prospecting License with twelve tribes on three islands and set up 3 Landowner Trusts.
	
	Reduced Community Development operational costs by $3m and Tenancy statutory costs by 75% (2008/09)

	Trained and mentored a local staff member to succeed me as the Manager of Community Development & Government Relations
</li>
<li>Project 3:	As Manager of Logistics I invoked and environmental scan of all logistical systems for the company, recommendation and redesign of systems, implementation process. The outcome was I mentored and trained local staff members and as a result three local staff to direct the Logistics section and reduced operational costs by $250,000 and increased operational efficiency by 50%.</li>

<p>As part of the Executive Management Team my redesign of the Community Relations and Logistics systems was a key determinant in the company successfully forming a joint venture with a major mining firm Anglo Gold Ashanti.</p>
