<h1>Pacifika Consultants – Positive Change Management Professionals</h1>

<h2>About</h2>

<p>Pacifika Consultants Ltd are change management professionals and provide relationshipmanagement,

cross cultural awareness and conflict resolution expertise. We work with a range of clients 

Internationally and locally and have achieved successful results throughout the Asia Pacific 

region. We add value to our clients by entering into collaborative relationships in which 

responsibility is shared, skills are transferred and dependence on us is diminished to the point 

of disengagement.</p>

<h3>Mission Statement</h3>

<p>To facilitate positive change in people’s lives</p>

<h3>Vision Statement:</h3>

<p>To become the organisation of choice in community facilitation</p>

<p>Organisational Values:</p>

<p>Honesty: We are open and transparent in the way we conduct our business</p>

<p>Respect: We demonstrate fairness, consistency, and empathy in our interactions with others</p>

<p>Trust:  We are reliable, dependable and accountable for our actions</p>

<p>Integrity: We are professional and ethical in all that we do</p>