<h3>Senior Advisor – Newmont Asia Pacific</h3>

<p>Newmont Asia Pacific is a major mining company and the second largest producer of the world’s gold.</p>

<p>Newmont Ventures Ltd - Solomon Islands</p>

<ul>
	<li><p>To act as an In-Country Advisor on Community Relations, Stakeholder Engagement and Conflict Resolution strategies.</p></li>
	<li><p>To improve and enhance internal cross functional relationships.</p></li>
	<li><p>The redesign, development and implementation of policies, processes, systems and standard operating procedures to enhance the efficiencies of the Social Responsibility systems.</p></li>
	<li><p>Train and build the capacity and capability of national Solomon Island Community Realtions staff.</p></li>
</ul>

<h3>Solomon Islands – Pacific Porphyry SI Ltd. subsidiary of XDM Resources</h3> 

<p>Mineral Extractive Industry - Generative Exploration – Gold & Copper</p>

<p>Project was based in the Solomon Islands and predominantly in the Western Province (Morovo Lagoon, New Georgia Island, Vela Lavela Island). Three projects were completed over a 2 year period being:</p>

<ul>
<li><p>Project 1: 	A business improvement process for 4 tenement camps which involved an environmental scan of all logistical systems, recommendation and redesign of systems, implementation process. The outcome was operational efficiencies resulting in a reduction of operational costs.</p></li>

<li><p>Project 2:	As Manager of Community Development & Government Relations I led a team that achieved and negotiated the renewal of four Prospecting Licenses, six Surface Access Agreements, and one new Prospecting License with twelve tribes on three islands and set up 3 Landowner Trusts.</p>
	
	<p><i>Reduced Community Development operational costs by $3m and Tenancy statutory costs by 75% (2008/09)</i></p>

	<p><i>Trained and mentored a local staff member to succeed me as the Manager of Community Development & Government Relations</i></p>
</li>

<li><p>Project 3:	As Manager of Logistics I invoked and environmental scan of all logistical systems for the company, recommendation and redesign of systems, implementation process. The outcome was I mentored and trained local staff members and as a result three local staff to direct the Logistics section and reduced operational costs by $250,000 and increased operational efficiency by 50%.</p>

<p>As part of the Executive Management Team my redesign of the Community Relations and Logistics systems was a key determinant in the company successfully forming a joint venture with a major mining firm Anglo Gold Ashanti.</p></li>
</ul>

<h3>Solomon Islands – Pacific Porphyry SI Ltd. subsidiary of XDM Resources</h3>

<p>Mineral Extractive Industry - Generative Exploration – Gold & Copper</p>

<p>Project was based in the Solomon Islands and predominantly in the Western Province (Morovo Lagoon, New Georgia Island, Vela Lavela Island). Three projects were completed over a 2 year period being:</p>

<ul>
<li><p>Project 1: 	A business improvement process for 4 tenement camps which involved an environmental scan of all logistical systems, recommendation and redesign of systems, implementation process. The outcome was operational efficiencies resulting in a reduction of operational costs.</p></li>

<li><p>Project 2:	As Manager of Community Development & Government Relations I led a team that achieved and negotiated the renewal of four Prospecting Licenses, six Surface Access Agreements, and one new Prospecting License with twelve tribes on three islands and set up 3 Landowner Trusts.
	
	Reduced Community Development operational costs by $3m and Tenancy statutory costs by 75% (2008/09)

	Trained and mentored a local staff member to succeed me as the Manager of Community Development & Government Relations</p>
</li>
<li>Project 3:	As Manager of Logistics I invoked and environmental scan of all logistical systems for the company, recommendation and redesign of systems, implementation process. The outcome was I mentored and trained local staff members and as a result three local staff to direct the Logistics section and reduced operational costs by $250,000 and increased operational efficiency by 50%.</li>

<p>As part of the Executive Management Team my redesign of the Community Relations and Logistics systems was a key determinant in the company successfully forming a joint venture with a major mining firm Anglo Gold Ashanti.</p>