<div class="row">
    <div id="card-container" class="large-12 columns text-center">
        <img class="card" src="/images/card-front.jpg" title="Pacifika Consultants">
    </div>
</div>
<script type="text/javascript" src="/js/jquery.flippy.js"></script>
        <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
<script>
    $(document).ready(function(){
        $('#card-container').on('click', '.card', function(){
            $('#card-container').flippy({
                color_target: 'white',
                duration: '500',
                verso: '<img class="card-back" src="/images/card-back.jpg" title="Pacifika Consultants">'
            })
     });
        $('#card-container').on('click', '.card-back', function(){
            $('.card-back').on('click', function(){
                $('#card-container').flippy({
                    color_target: 'white',
                    duration: '500',
                    verso: '<img class="card" src="/images/card-front.jpg" title="Pacifika Consultants">'
                })
            });
        });
    });
</script>